
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'finance'
version: '1.0.0'
config-version: 2

dbt-cloud:
    project-id: 70471823483500
    
# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# snapshots:
#   finance:
#     +target_schema: db_snapshots
#     +materialized: snapshot

# snapshots:
#   finance:
#     +unique_key: "id"
#     +schema: "snapshots"
#     +database: "db_snapshots"
    # +alias: <string>
    # +unique_key: <column_name_or_expression>
    # +strategy: check
    # +updated_at: <column_name>
    # +check_cols: [<column_name>] | all
    # +snapshot_meta_column_names: {<dictionary>}
    # +dbt_valid_to_current: <string> 
    # +hard_deletes: string

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
    finance:
      mart:
        +materialized: table
        finance:
          +schema: finance
      # python:
      #   submission_method: bigframes
      #     python_models:
      #         +materialized: view