version: 2

sources:
  - name: raw # required
    description: GreenWeez Raw Dataset
    # database: <database_name>
    schema: gz_raw_data
    # loader: <string>
    # loaded_at_field: <column_name>
    # meta: {<dictionary>}
    # tags: [<string>]
    
    # # requires v1.1+
    # config:
    #   <source_config>: <config_value>
    #   freshness: 
    #     # changed to config in v1.9
    #     warn_after:
    #       count: <positive_integer>
    #       period: minute | hour | day
    #     error_after:
    #       count: <positive_integer>
    #       period: minute | hour | day
    #     filter: <where-condition>
      
    # overrides: <string>

    # quoting:
    #   database: true | false
    #   schema: true | false
    #   identifier: true | false

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: has raw sales data entity
        # constraints:
        #   - type: primary_key
        #     columns: [orders_id, pdt_id]
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        config:
          freshness:
            warn_after:
              count: 90
              period: day
            # error_after:
            #   count: 4
            #   period: day
        columns:
          - name: date_date # required
            description: sales of Greenweez / order date

            # description: <markdown_string>
            # tests:
            #   - test_case # declare  tests
          - name: orders_id # required
            description: sales of Greenweez / we have on row per product_id found in each orders_id
          - name: pdt_id
            description: product ID / reference key for products table
          - name: revenue
            description: total turnover per order
          - name: quantity
            description: quanity of products per order
            # description: <markdown_string>
            # tests:
            #   - test_case # declare  tests
        # tests:
          # - unique:
          #     combination_of: ['orders_id', 'pdt_id']
          # - dbt_utils.unique_combination_of_columns:
          #   combination_of_columns:
          #     - orders_id
          #     - pdt_id


      - name: product
        identifier: raw_gz_product
        description: Has raw product data entity
        columns:
          - name: products_id
            description: unique product ID for GWZ
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: product purchase price

      - name: ship
        identifier: raw_gz_ship
        description: Has raw shipping data entity
        columns:
          - name: orders_id
            description: FK / PK for sales table / order id for the shipment
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee charged from the client
          - name: shipping_fee_1
          - name: logCost
            description: actual logging cost for the shipping
          - name: ship_cost
            description: actual shipping cost incurred for the shipment

      # - name: <string> #required
      #   description: <markdown_string>
      #   # meta: {<dictionary>}
      #   # identifier: <table_name>
      #   # loaded_at_field: <column_name>
      #   tests:
      #     - <test>
      #     - ... # declare additional tests
      #   # tags: [<string>]
      #   # config:
      #   #   freshness:
      #   #     warn_after:
      #   #       count: <positive_integer>
      #   #       period: minute | hour | day
      #   #     error_after:
      #   #       count: <positive_integer>
      #   #       period: minute | hour | day
      #   #     filter: <where-condition>

      #   # quoting:
      #   #   database: true | false
      #   #   schema: true | false
      #   #   identifier: true | false
      #   # external: {<dictionary>}
      #   columns:
      #     - name: <column_name> # required
      #       description: <markdown_string>
      #       meta: {<dictionary>}
      #       quote: true | false
      #       tests:
      #         - <test>
      #         - ... # declare additional tests
      #       tags: [<string>]
      #     - name: ... # declare properties of additional columns

      # - name: ... # declare properties of additional source tables

  # - name: ... # declare properties of additional sources


models:
  - name: finance_days
    description: Final aggregated table for sales team
    columns:
      - name: date_date
        description: PK for the table
        tests:
          - unique
          - not_null
      - name: transactions_count
        description: count of transaction on a day
      - name: total_revenue
        description: total revenue for the day
      - name: average_basket_value
        description: daily average_basket_value
      - name: margin
        description: total margin for the day
      - name: operational_margin
        description: total margin minus operation cost
      - name: total_purchase_cost
        description: total purchase cost for the day
      - name: total_log_cost
        description: actual total cost for logging
      - name: total_ship_cost
        description: actual total cost for shipping per day
      - name: total_quantity_sold
        description: total products quanity sold for the day

  - name: int_orders_margin
    description: Final aggregated table for sales team
    columns:
      - name: date_date
        description: date of the order
      - name: orders_id
        description: orders identification number
        # tests:
        #   - unique
        #   - not_null
      - name: products_id
        description: product identification number
      - name: revenue
        description: totoal turover of the order
      - name: quantity
        description: products quantity shipped with the order
      - name: purchase_cost
        description: purchase cost - total price for the quantity in order
      - name: margin
        description: total margin per order

  - name: int_orders_operational
    description: Final aggregated table for sales team
    columns:
      - name: date_date
        description: date of the order
      - name: orders_id
        description: orders identification number
        # tests:
        #   - unique
        #   - not_null
      - name: products_id
        description: product identification number
      - name: revenue
        description: totoal turover of the order
      - name: quantity
        description: products quantity shipped with the order
      - name: purchase_cost
        description: purchase cost - total price for the quantity in order
      - name: margin
        description: total margin per order
      - name: log_cost
        description: actual cost for logging
      - name: ship_cost
        description: actual cost for shipping per order
      - name: operational_margin
        description: margin minus operation cost

  - name: int_sales_margin
    description: Final aggregated table for sales team
    columns:
      - name: date_date
        description: date of the order
      - name: orders_id
        description: orders identification number
        # tests:
        #   - unique
        #   - not_null
      - name: products_id
        description: product identification number
      - name: revenue
        description: totoal turover of the order
      - name: quantity
        description: products quantity shipped with the order
      - name: purchase_cost
        description: purchase cost - total price for the quantity in order

  - name: stg_product
    description: Final aggregated table for sales team
    columns:
      - name: products_id
        description: PK for the table
        tests:
          - unique
          - not_null
      - name: purchase_price
        description: set price for the product

  - name: stg_sales
    description: Final aggregated table for sales team
    columns:
      - name: date_date
        description: date of the order
      - name: orders_id
        description: orders identification number
        # tests:
        #   - unique
        #   - not_null
      - name: products_id
        description: product identification number
      - name: revenue
        description: totoal turover of the order
      - name: quantity
        description: products quantity shipped with the order
    
  - name: stg_ship
    description: Final aggregated table for sales team
    columns:
      - name: orders_id
        description: PK for the table
        tests:
          - unique
          - not_null
      - name: shipping_fee
        description: shipping fee charged on customer
      - name: log_cost
        description: actual cost for logging
      - name: ship_cost
        description: actual cost for shipping per order